diff --git a/examples/demo/client/Makefile b/examples/demo/client/Makefile
deleted file mode 100644
index bdd863a20..000000000
--- a/examples/demo/client/Makefile
+++ /dev/null
@@ -1 +0,0 @@
-include ../../../Makefile.Common
