diff --git a/Makefile b/Makefile
index adefd0f64..4d59e1ab6 100644
--- a/Makefile
+++ b/Makefile
@@ -283,6 +283,7 @@ check-contrib:
 		-replace go.opentelemetry.io/collector/confmap/provider/httpsprovider=$(CURDIR)/confmap/provider/httpsprovider  \
 		-replace go.opentelemetry.io/collector/confmap/provider/yamlprovider=$(CURDIR)/confmap/provider/yamlprovider  \
 		-replace go.opentelemetry.io/collector/connector=$(CURDIR)/connector  \
+		-replace go.opentelemetry.io/collector/connector/connectortest=$(CURDIR)/connector/connectortest  \
 		-replace go.opentelemetry.io/collector/connector/connectorprofiles=$(CURDIR)/connector/connectorprofiles  \
 		-replace go.opentelemetry.io/collector/connector/forwardconnector=$(CURDIR)/connector/forwardconnector  \
 		-replace go.opentelemetry.io/collector/consumer=$(CURDIR)/consumer  \
@@ -355,6 +356,7 @@ restore-contrib:
 		-dropreplace go.opentelemetry.io/collector/confmap/provider/httpsprovider  \
 		-dropreplace go.opentelemetry.io/collector/confmap/provider/yamlprovider  \
 		-dropreplace go.opentelemetry.io/collector/connector  \
+		-dropreplace go.opentelemetry.io/collector/connector/connectortest  \
 		-dropreplace go.opentelemetry.io/collector/connector/connectorprofiles  \
 		-dropreplace go.opentelemetry.io/collector/connector/forwardconnector  \
 		-dropreplace go.opentelemetry.io/collector/consumer  \
