diff --git a/extension/experimental/storage/Makefile b/extension/experimental/storage/Makefile
deleted file mode 100644
index bdd863a20..000000000
--- a/extension/experimental/storage/Makefile
+++ /dev/null
@@ -1 +0,0 @@
-include ../../../Makefile.Common
