diff --git a/extension/extensionmiddleware/extensionmiddlewaretest/Makefile b/extension/extensionmiddleware/extensionmiddlewaretest/Makefile
new file mode 100644
index 000000000..bdd863a20
--- /dev/null
+++ b/extension/extensionmiddleware/extensionmiddlewaretest/Makefile
@@ -0,0 +1 @@
+include ../../../Makefile.Common
