diff --git a/Makefile b/Makefile
index 5899559ad..eb926b030 100644
--- a/Makefile
+++ b/Makefile
@@ -22,6 +22,7 @@ ADDLICENCESE= addlicense
 MISSPELL=misspell -error
 MISSPELL_CORRECTION=misspell -w
 STATICCHECK=staticcheck
+IMPI=impi
 
 GIT_SHA=$(shell git rev-parse --short HEAD)
 BUILD_INFO_IMPORT_PATH=github.com/open-telemetry/opentelemetry-collector/internal/version
@@ -37,10 +38,10 @@ all-pkgs:
 all-srcs:
 	@echo $(ALL_SRC) | tr ' ' '\n' | sort
 
-.DEFAULT_GOAL := addlicense-fmt-vet-lint-goimports-misspell-staticcheck-test
+.DEFAULT_GOAL := addlicense-fmt-impi-vet-lint-goimports-misspell-staticcheck-test
 
-.PHONY: addlicense-fmt-vet-lint-goimports-misspell-staticcheck-test
-addlicense-fmt-vet-lint-goimports-misspell-staticcheck-test: addlicense fmt vet lint goimports misspell staticcheck test
+.PHONY: addlicense-fmt-impi-vet-lint-goimports-misspell-staticcheck-test
+addlicense-fmt-impi-vet-lint-goimports-misspell-staticcheck-test: addlicense fmt impi vet lint goimports misspell staticcheck test
 
 .PHONY: e2e-test
 e2e-test: otelcol
@@ -55,7 +56,7 @@ benchmark:
 	$(GOTEST) -bench=. -run=notests $(ALL_PKGS)
 
 .PHONY: travis-ci
-travis-ci: fmt vet lint goimports misspell staticcheck test-with-cover otelcol
+travis-ci: fmt impi vet lint goimports misspell staticcheck test-with-cover otelcol
 	$(MAKE) -C testbed install-tools
 	$(MAKE) -C testbed runtests
 
@@ -129,6 +130,10 @@ vet:
 	@$(GOVET) ./...
 	@echo "Vet finished successfully"
 
+.PHONY: impi
+impi:
+	@$(IMPI) --local github.com/open-telemetry/opentelemetry-collector --scheme stdThirdPartyLocal ./...
+
 .PHONY: install-tools
 install-tools:
 	GO111MODULE=on go install \
@@ -136,7 +141,8 @@ install-tools:
 	  golang.org/x/lint/golint \
 	  golang.org/x/tools/cmd/goimports \
 	  github.com/client9/misspell/cmd/misspell \
-	  honnef.co/go/tools/cmd/staticcheck
+	  honnef.co/go/tools/cmd/staticcheck \
+	  github.com/pavius/impi/cmd/impi
 
 .PHONY: otelcol
 otelcol:
