diff --git a/extension/extensionauth/extensionauthtest/Makefile b/extension/extensionauth/extensionauthtest/Makefile
new file mode 100644
index 000000000..bdd863a20
--- /dev/null
+++ b/extension/extensionauth/extensionauthtest/Makefile
@@ -0,0 +1 @@
+include ../../../Makefile.Common
