diff --git a/Makefile b/Makefile
index a1061e5b6..59a540837 100644
--- a/Makefile
+++ b/Makefile
@@ -218,7 +218,6 @@ gendependabot: $(eval SHELL:=/bin/bash)
 	@echo "version: 2" >> ${DEPENDABOT_PATH}
 	@echo "updates:" >> ${DEPENDABOT_PATH}
 	$(MAKE) internal-gendependabot DIR="/" PACKAGE="github-actions"
-	$(MAKE) internal-gendependabot DIR="/" PACKAGE="docker"
 	$(MAKE) internal-gendependabot DIR="/" PACKAGE="gomod"
 	@set -e; for dir in $(ALL_MODULES); do \
 		$(MAKE) internal-gendependabot DIR=$${dir:1} PACKAGE="gomod"; \
