diff --git a/pipeline/pipelineprofiles/Makefile b/pipeline/pipelineprofiles/Makefile
new file mode 100644
index 000000000..ded7a3609
--- /dev/null
+++ b/pipeline/pipelineprofiles/Makefile
@@ -0,0 +1 @@
+include ../../Makefile.Common
