diff --git a/cmd/builder/Makefile b/cmd/builder/Makefile
index ded7a3609..59bde9344 100644
--- a/cmd/builder/Makefile
+++ b/cmd/builder/Makefile
@@ -1 +1,5 @@
 include ../../Makefile.Common
+
+.PHONY: ocb
+ocb:
+	GO111MODULE=on CGO_ENABLED=0 $(GOCMD) build -trimpath -o ../../bin/ocb_$(GOOS)_$(GOARCH) .
