diff --git a/Makefile b/Makefile
index e818b32e1..61b5de5fc 100644
--- a/Makefile
+++ b/Makefile
@@ -14,6 +14,7 @@ GOFMT=gofmt
 GOLINT=golint
 GOVET=go vet
 GOOS=$(shell go env GOOS)
+ADDLICENCESE= addlicense
 
 GIT_SHA=$(shell git rev-parse --short HEAD)
 BUILD_INFO_IMPORT_PATH=github.com/open-telemetry/opentelemetry-service/internal/version
@@ -29,10 +30,10 @@ all-pkgs:
 all-srcs:
 	@echo $(ALL_SRC) | tr ' ' '\n' | sort
 
-.DEFAULT_GOAL := fmt-vet-lint-test
+.DEFAULT_GOAL := addlicense-fmt-vet-lint-test
 
-.PHONY: fmt-vet-lint-test
-fmt-vet-lint-test: fmt vet lint test
+.PHONY: addlicense-fmt-vet-lint-test
+addlicense-fmt-vet-lint-test: addlicense fmt vet lint test
 
 .PHONY: e2e-test
 e2e-test: otelsvc
@@ -56,6 +57,17 @@ test-with-cover:
 	$(GOTEST) $(GOTEST_OPT_WITH_COVERAGE) $(ALL_PKGS)
 	go tool cover -html=coverage.txt -o coverage.html
 
+.PHONY: addlicense
+addlicense:
+	@ADDLICENCESEOUT=`$(ADDLICENCESE) -y 2019 -c 'OpenTelemetry Authors' $(ALL_SRC) 2>&1`; \
+		if [ "$$ADDLICENCESEOUT" ]; then \
+			echo "$(ADDLICENCESE) FAILED => add License errors:\n"; \
+			echo "$$ADDLICENCESEOUT\n"; \
+			exit 1; \
+		else \
+			echo "Add License finished successfully"; \
+		fi
+
 .PHONY: fmt
 fmt:
 	@FMTOUT=`$(GOFMT) -s -l $(ALL_SRC) 2>&1`; \
