diff --git a/Makefile b/Makefile
index 30bb66ed8..cfb2973df 100644
--- a/Makefile
+++ b/Makefile
@@ -78,7 +78,7 @@ vet:
 
 .PHONY: install-tools
 install-tools:
-	go get golang.org/x/lint/golint
+	go get -u golang.org/x/lint/golint
 	go get -u github.com/google/go-cmp/cmp
 	go get contrib.go.opencensus.io/exporter/jaeger@v0.1.1-0.20190430175949-e8b55949d948
 	go get contrib.go.opencensus.io/exporter/prometheus
