diff --git a/config/internal/Makefile b/config/internal/Makefile
deleted file mode 100644
index ded7a3609..000000000
--- a/config/internal/Makefile
+++ /dev/null
@@ -1 +0,0 @@
-include ../../Makefile.Common
