diff --git a/internal/buildscripts/packaging/fpm/Dockerfile b/internal/buildscripts/packaging/fpm/Dockerfile
new file mode 100644
index 000000000..bdc36c6fa
--- /dev/null
+++ b/internal/buildscripts/packaging/fpm/Dockerfile
@@ -0,0 +1,16 @@
+FROM debian:9
+
+RUN apt-get update && \
+    apt-get install -y ruby ruby-dev rubygems build-essential git rpm
+
+RUN gem install --no-document fpm -v 1.11.0
+
+VOLUME /repo
+WORKDIR /repo
+
+ENV PACKAGE="deb"
+ENV VERSION=""
+ENV ARCH="amd64"
+ENV OUTPUT_DIR="/repo/bin/"
+
+CMD ./internal/buildscripts/packaging/fpm/$PACKAGE/build.sh "$VERSION" "$ARCH" "$OUTPUT_DIR"
\ No newline at end of file
