diff --git a/internal/cmd/pdatagen/Makefile b/internal/cmd/pdatagen/Makefile
new file mode 100644
index 000000000..bdd863a20
--- /dev/null
+++ b/internal/cmd/pdatagen/Makefile
@@ -0,0 +1 @@
+include ../../../Makefile.Common
