diff --git a/receiver/otlpreceiver/Makefile b/receiver/otlpreceiver/Makefile
new file mode 100644
index 000000000..ded7a3609
--- /dev/null
+++ b/receiver/otlpreceiver/Makefile
@@ -0,0 +1 @@
+include ../../Makefile.Common
