diff --git a/exporter/exporterhelper/exporterhelperprofiles/Makefile b/exporter/exporterhelper/exporterhelperprofiles/Makefile
new file mode 100644
index 000000000..bdd863a20
--- /dev/null
+++ b/exporter/exporterhelper/exporterhelperprofiles/Makefile
@@ -0,0 +1 @@
+include ../../../Makefile.Common
