diff --git a/Makefile b/Makefile
index 53ce92e52..96015311c 100644
--- a/Makefile
+++ b/Makefile
@@ -172,7 +172,7 @@ otelcorecol:
 		$(BUILD_INFO) -tags $(GO_BUILD_TAGS) ./cmd/otelcorecol && popd
 
 .PHONY: genotelcorecol
-genotelcorecol:
+genotelcorecol: install-tools
 	pushd cmd/builder/ && $(GOCMD) run ./ --skip-compilation --config ../otelcorecol/builder-config.yaml --output-path ../otelcorecol && popd
 	$(MAKE) -C cmd/otelcorecol fmt
 
