diff --git a/component/componentprofiles/Makefile b/component/componentprofiles/Makefile
new file mode 100644
index 000000000..ded7a3609
--- /dev/null
+++ b/component/componentprofiles/Makefile
@@ -0,0 +1 @@
+include ../../Makefile.Common
