diff --git a/Makefile b/Makefile
index 0c99dde81..6d9c8b230 100644
--- a/Makefile
+++ b/Makefile
@@ -144,14 +144,15 @@ fmt:
 .PHONY: install-tools
 install-tools:
 	go install github.com/client9/misspell/cmd/misspell
-	go install github.com/google/addlicense
 	go install github.com/golangci/golangci-lint/cmd/golangci-lint
+	go install github.com/google/addlicense
 	go install github.com/jstemmer/go-junit-report
+	go install github.com/mjibson/esc
 	go install github.com/ory/go-acc
 	go install github.com/pavius/impi/cmd/impi
 	go install github.com/securego/gosec/cmd/gosec
-	go install honnef.co/go/tools/cmd/staticcheck
 	go install github.com/tcnksm/ghr
+	go install honnef.co/go/tools/cmd/staticcheck
 
 .PHONY: otelcol
 otelcol:
