diff --git a/Makefile b/Makefile
index dc7884c89..925cb18a5 100644
--- a/Makefile
+++ b/Makefile
@@ -3,6 +3,7 @@ include ./Makefile.Common
 # This is the code that we want to run lint, etc.
 ALL_SRC := $(shell find . -name '*.go' \
 							-not -path './internal/tools/*' \
+							-not -path '*/third_party/*' \
 							-not -path './pdata/internal/data/protogen/*' \
 							-not -path './service/internal/zpages/tmplgen/*' \
 							-type f | sort)
@@ -57,7 +58,7 @@ gotest-with-cover:
 
 .PHONY: goporto
 goporto: $(PORTO)
-	$(PORTO) -w --include-internal ./
+	$(PORTO) -w --include-internal --skip-dirs "^cmd/mdatagen/third_party$$" ./
 
 .PHONY: golint
 golint:
@@ -77,7 +78,9 @@ gotidy:
 
 .PHONY: gogenerate
 gogenerate:
+	cd cmd/mdatagen && $(GOCMD) install .
 	@$(MAKE) for-all-target TARGET="generate"
+	$(MAKE) fmt
 
 .PHONY: addlicense
 addlicense: $(ADDLICENSE)
