diff --git a/consumer/consumerprofiles/Makefile b/consumer/consumerprofiles/Makefile
new file mode 100644
index 000000000..ded7a3609
--- /dev/null
+++ b/consumer/consumerprofiles/Makefile
@@ -0,0 +1 @@
+include ../../Makefile.Common
