diff --git a/consumer/xconsumer/Makefile b/consumer/xconsumer/Makefile
new file mode 100644
index 000000000..ded7a3609
--- /dev/null
+++ b/consumer/xconsumer/Makefile
@@ -0,0 +1 @@
+include ../../Makefile.Common
