diff --git a/examples/demo/server/Makefile b/examples/demo/server/Makefile
new file mode 100644
index 000000000..bdd863a20
--- /dev/null
+++ b/examples/demo/server/Makefile
@@ -0,0 +1 @@
+include ../../../Makefile.Common
