diff --git a/examples/demo/client/Dockerfile b/examples/demo/client/Dockerfile
index f4de9763f..4ffbb23c4 100644
--- a/examples/demo/client/Dockerfile
+++ b/examples/demo/client/Dockerfile
@@ -11,7 +11,7 @@
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
-FROM golang:1.16
+FROM golang:1.17
 COPY . /usr/src/client/
 WORKDIR /usr/src/client/
 RUN go env -w GOPROXY=direct
