diff --git a/confmap/provider/yamlprovider/Makefile b/confmap/provider/yamlprovider/Makefile
new file mode 100644
index 000000000..bdd863a20
--- /dev/null
+++ b/confmap/provider/yamlprovider/Makefile
@@ -0,0 +1 @@
+include ../../../Makefile.Common
