diff --git a/pipeline/pipelineprofiles/Makefile b/pipeline/pipelineprofiles/Makefile
deleted file mode 100644
index ded7a3609..000000000
--- a/pipeline/pipelineprofiles/Makefile
+++ /dev/null
@@ -1 +0,0 @@
-include ../../Makefile.Common
