diff --git a/Makefile b/Makefile
index 6954be97c..b6f7fc132 100644
--- a/Makefile
+++ b/Makefile
@@ -60,10 +60,6 @@ gotest-with-cover:
 gotest-with-junit:
 	@$(MAKE) for-all-target TARGET="test-with-junit"
 
-.PHONY: gotestifylint-fix
-gotestifylint-fix:
-	$(MAKE) for-all-target TARGET="testifylint-fix"
-
 .PHONY: goporto
 goporto: $(PORTO)
 	$(PORTO) -w --include-internal --skip-dirs "^cmd/mdatagen/third_party$$" ./
