diff --git a/exporter/nopexporter/Makefile b/exporter/nopexporter/Makefile
new file mode 100644
index 000000000..ded7a3609
--- /dev/null
+++ b/exporter/nopexporter/Makefile
@@ -0,0 +1 @@
+include ../../Makefile.Common
