diff --git a/Makefile b/Makefile
index bc70f1da1..4e33cb9c7 100644
--- a/Makefile
+++ b/Makefile
@@ -10,7 +10,7 @@ ALL_DOC := $(shell find . \( -name "*.md" -o -name "*.yaml" \) \
 # ALL_PKGS is used with 'go cover'
 ALL_PKGS := $(shell go list $(sort $(dir $(ALL_SRC))))
 
-GOTEST_OPT?= -race -timeout 30s
+GOTEST_OPT?= -race -timeout 180s
 GOTEST_OPT_WITH_COVERAGE = $(GOTEST_OPT) -coverprofile=coverage.txt -covermode=atomic
 GOTEST=go test
 GOOS=$(shell go env GOOS)
@@ -48,7 +48,7 @@ e2e-test: otelcol
 
 .PHONY: test
 test:
-	$(GOTEST) $(GOTEST_OPT) $(ALL_PKGS)
+	echo $(ALL_PKGS) | xargs -n 10 $(GOTEST) $(GOTEST_OPT)
 
 .PHONY: benchmark
 benchmark:
@@ -65,8 +65,9 @@ test-with-cover:
 	@scripts/check-test-files.sh $(subst github.com/open-telemetry/opentelemetry-collector/,./,$(ALL_PKGS))
 	@echo pre-compiling tests
 	@time go test -i $(ALL_PKGS)
-	$(GOTEST) $(GOTEST_OPT_WITH_COVERAGE) $(ALL_PKGS)
-	go tool cover -html=coverage.txt -o coverage.html
+	echo "mode: atomic" > coverage_all.txt
+	echo $(ALL_PKGS) | xargs -n 10 bash -c 'mv coverage_all.txt coverage_old.txt; $(GOTEST) $(GOTEST_OPT_WITH_COVERAGE) "$$@"; gocovmerge coverage_old.txt coverage.txt > coverage_all.txt' ''
+	go tool cover -html=coverage_all.txt -o coverage.html
 
 .PHONY: addlicense
 addlicense:
@@ -123,6 +124,7 @@ install-tools:
 	go install github.com/pavius/impi/cmd/impi
 	go install github.com/securego/gosec/cmd/gosec
 	go install honnef.co/go/tools/cmd/staticcheck
+	go install github.com/wadey/gocovmerge
 
 .PHONY: otelcol
 otelcol:
@@ -150,7 +152,7 @@ binaries: otelcol
 
 .PHONY: binaries-all-sys
 binaries-all-sys:
-	GOOS=darwin GOARCH=amd64 $(MAKE) binaries
-	GOOS=linux GOARCH=amd64 $(MAKE) binaries
-	GOOS=linux GOARCH=arm64 $(MAKE) binaries
+	GOOS=darwin  GOARCH=amd64 $(MAKE) binaries
+	GOOS=linux   GOARCH=amd64 $(MAKE) binaries
+	GOOS=linux   GOARCH=arm64 $(MAKE) binaries
 	GOOS=windows GOARCH=amd64 $(MAKE) binaries
