diff --git a/internal/globalgates/Makefile b/internal/globalgates/Makefile
deleted file mode 100644
index ded7a3609..000000000
--- a/internal/globalgates/Makefile
+++ /dev/null
@@ -1 +0,0 @@
-include ../../Makefile.Common
