diff --git a/Makefile b/Makefile
index c05f41912..a53159641 100644
--- a/Makefile
+++ b/Makefile
@@ -19,6 +19,7 @@ TOOLS_MOD_DIR := ./internal/tools
 
 GOOS=$(shell $(GOCMD) env GOOS)
 GOARCH=$(shell $(GOCMD) env GOARCH)
+GH := $(shell which gh)
 
 # TODO: Find a way to configure this in the generated code, currently no effect.
 BUILD_INFO_IMPORT_PATH=go.opentelemetry.io/collector/internal/version
@@ -369,3 +370,46 @@ multimod-verify: install-tools
 multimod-prerelease: install-tools
 	multimod prerelease -v ./versions.yaml -m collector-core
 	$(MAKE) gotidy
+
+.PHONY: prepare-release
+prepare-release:
+ifdef PREVIOUS_VERSION
+	@echo "Previous version $(PREVIOUS_VERSION)"
+else
+	@echo "PREVIOUS_VERSION not defined"
+	@echo "usage: make prepare-release RELEASE_CANDIDATE=<version eg 0.53.0> PREVIOUS_VERSION=<version eg 0.52.0>"
+	exit 1
+endif
+ifdef RELEASE_CANDIDATE
+	@echo "Preparing release $(RELEASE_CANDIDATE)"
+else
+	@echo "RELEASE_CANDIDATE not defined"
+	@echo "usage: make prepare-release RELEASE_CANDIDATE=<version eg 0.53.0> PREVIOUS_VERSION=<version eg 0.52.0>"
+	exit 1
+endif
+	# ensure a clean branch
+	git diff -s --exit-code || (echo "local repository not clean"; exit 1)
+	# TODO: update changelog
+	# update versions.yaml config.go builder-config.yaml
+	sed -i.bak 's/$(PREVIOUS_VERSION)/$(RELEASE_CANDIDATE)/g' versions.yaml
+	sed -i.bak 's/$(PREVIOUS_VERSION)/$(RELEASE_CANDIDATE)/g' ./cmd/builder/internal/builder/config.go
+	sed -i.bak 's/$(PREVIOUS_VERSION)/$(RELEASE_CANDIDATE)/g' ./cmd/otelcorecol/builder-config.yaml
+	sed -i.bak 's/$(PREVIOUS_VERSION)/$(RELEASE_CANDIDATE)/g' examples/k8s/otel-config.yaml
+	find . -name "*.bak" -type f -delete
+	# regenerate files
+	$(MAKE) genotelcorecol
+	# commit changes before running multimod
+	git checkout -b opentelemetry-collector-bot/release-$(RELEASE_CANDIDATE)
+	git add .
+	git commit -m "prepare release $(RELEASE_CANDIDATE)"
+	$(MAKE) multimod-prerelease
+	# commit multimod changes
+	git add .
+	git commit -m "add multimod changes" || (echo "no multimod changes to commit")
+	git push fork opentelemetry-collector-bot/release-$(RELEASE_CANDIDATE)
+	@if [ -z "$(GH)" ]; then \
+		echo "'gh' command not found, can't submit the PR on your behalf."; \
+		exit 1; \
+	fi
+	gh pr create --title "[chore] prepare release $(RELEASE_CANDIDATE)"
+
