diff --git a/Makefile b/Makefile
index f9dc945b2..7d733e090 100644
--- a/Makefile
+++ b/Makefile
@@ -13,11 +13,7 @@ ALL_DOC := $(shell find . \( -name "*.md" -o -name "*.yaml" \) \
                                 -type f | sort)
 
 # ALL_MODULES includes ./* dirs (excludes . dir)
-ALL_MODULES := $(shell find . -mindepth 2 \
-				-type f \
-				-name "go.mod" \
-				-not -path "./internal/tools/*" \
-				-exec dirname {} \; | sort )
+ALL_MODULES := $(shell find . -type f -name "go.mod" -exec dirname {} \; | sort | grep -E '^./' )
 
 CMD?=
 
@@ -65,8 +61,8 @@ gotest-with-junit:
 	@$(MAKE) for-all-target TARGET="test-with-junit"
 
 .PHONY: goporto
-goporto:
-	$(GO_TOOL) porto -w --include-internal --skip-dirs "^cmd/mdatagen/third_party$$" ./
+goporto: $(PORTO)
+	$(PORTO) -w --include-internal --skip-dirs "^cmd/mdatagen/third_party$$" ./
 
 .PHONY: for-all
 for-all:
@@ -105,8 +101,8 @@ govulncheck:
 	@$(MAKE) for-all-target TARGET="vulncheck"
 
 .PHONY: addlicense
-addlicense:
-	@ADDLICENSEOUT=`$(GO_TOOL) addlicense -s=only -y "" -c "The OpenTelemetry Authors" $(ALL_SRC) 2>&1`; \
+addlicense: $(ADDLICENSE)
+	@ADDLICENSEOUT=`$(ADDLICENSE) -s=only -y "" -c "The OpenTelemetry Authors" $(ALL_SRC) 2>&1`; \
 		if [ "$$ADDLICENSEOUT" ]; then \
 			echo "$(ADDLICENSE) FAILED => add License errors:\n"; \
 			echo "$$ADDLICENSEOUT\n"; \
@@ -116,7 +112,7 @@ addlicense:
 		fi
 
 .PHONY: checklicense
-checklicense:
+checklicense: $(ADDLICENSE)
 	@licRes=$$(for f in $$(find . -type f \( -iname '*.go' -o -iname '*.sh' \) ! -path '**/third_party/*') ; do \
 	           awk '/Copyright The OpenTelemetry Authors|generated|GENERATED/ && NR<=3 { found=1; next } END { if (!found) print FILENAME }' $$f; \
 			   awk '/SPDX-License-Identifier: Apache-2.0|generated|GENERATED/ && NR<=4 { found=1; next } END { if (!found) print FILENAME }' $$f; \
@@ -127,12 +123,12 @@ checklicense:
 	   fi
 
 .PHONY: misspell
-misspell:
-	$(GO_TOOL) misspell -error $(ALL_DOC)
+misspell: $(MISSPELL)
+	$(MISSPELL) -error $(ALL_DOC)
 
 .PHONY: misspell-correction
-misspell-correction:
-	$(GO_TOOL) misspell -w $(ALL_DOC)
+misspell-correction: $(MISSPELL)
+	$(MISSPELL) -w $(ALL_DOC)
 
 .PHONY: run
 run: otelcorecol
@@ -163,13 +159,13 @@ otelcorecol:
 	pushd cmd/otelcorecol && CGO_ENABLED=0 $(GOCMD) build -trimpath -o ../../bin/otelcorecol_$(GOOS)_$(GOARCH) -tags "grpcnotrace" ./... && popd
 
 .PHONY: genotelcorecol
-genotelcorecol:
+genotelcorecol: install-tools
 	pushd cmd/builder/ && $(GOCMD) run ./ --skip-compilation --config ../otelcorecol/builder-config.yaml --output-path ../otelcorecol && popd
 	$(MAKE) -C cmd/otelcorecol fmt
 
 .PHONY: actionlint
-actionlint:
-	$(GO_TOOL) actionlint -config-file .github/actionlint.yaml -color .github/workflows/*.yml .github/workflows/*.yaml
+actionlint: $(ACTIONLINT)
+	$(ACTIONLINT) -config-file .github/actionlint.yaml -color .github/workflows/*.yml .github/workflows/*.yaml
 
 .PHONY: ocb
 ocb:
@@ -250,10 +246,13 @@ genproto_sub:
 	@rm -rf $(OPENTELEMETRY_PROTO_SRC_DIR)/*
 	@rm -rf $(OPENTELEMETRY_PROTO_SRC_DIR)/.* > /dev/null 2>&1 || true
 
+remove-pdatagen:
+	rm -f .tools/pdatagen
+
 # Generate structs, functions and tests for pdata package. Must be used after any changes
 # to proto and after running `make genproto`
-genpdata:
-	cd internal/cmd/pdatagen && $(GOCMD) run main.go -C $(SRC_ROOT)
+genpdata: remove-pdatagen $(PDATAGEN)
+	$(PDATAGEN)
 	$(MAKE) -C pdata fmt
 
 INTERNAL_PROTO_SRC_DIRS := exporter/exporterhelper/internal/queue pdata/xpdata/request/internal
@@ -322,17 +321,17 @@ certs-dryrun:
 	@internal/buildscripts/gen-certs.sh -d
 
 .PHONY: checkapi
-checkapi:
-	$(GO_TOOL) checkapi -folder . -config .checkapi.yaml
+checkapi: $(CHECKAPI)
+	$(CHECKAPI) -folder . -config .checkapi.yaml
 
 # Verify existence of READMEs for components specified as default components in the collector.
 .PHONY: checkdoc
-checkdoc:
-	$(GO_TOOL) checkfile --project-path $(CURDIR) --component-rel-path $(COMP_REL_PATH) --module-name $(MOD_NAME) --file-name "README.md"
+checkdoc: $(CHECKFILE)
+	$(CHECKFILE) --project-path $(CURDIR) --component-rel-path $(COMP_REL_PATH) --module-name $(MOD_NAME) --file-name "README.md"
 
 # Construct new API state snapshots
 .PHONY: apidiff-build
-apidiff-build:
+apidiff-build: $(APIDIFF)
 	@$(foreach pkg,$(ALL_PKGS),$(call exec-command,./internal/buildscripts/gen-apidiff.sh -p $(pkg)))
 
 # If we are running in CI, change input directory
@@ -344,33 +343,33 @@ endif
 
 # Compare API state snapshots
 .PHONY: apidiff-compare
-apidiff-compare:
+apidiff-compare: $(APIDIFF)
 	@$(foreach pkg,$(ALL_PKGS),$(call exec-command,./internal/buildscripts/compare-apidiff.sh -p $(pkg)))
 
 .PHONY: multimod-verify
-multimod-verify:
+multimod-verify: $(MULTIMOD)
 	@echo "Validating versions.yaml"
-	$(GO_TOOL) multimod verify
+	$(MULTIMOD) verify
 
 MODSET?=stable
 .PHONY: multimod-prerelease
-multimod-prerelease:
-	$(GO_TOOL) multimod prerelease -s=true -b=false -v ./versions.yaml -m ${MODSET}
+multimod-prerelease: $(MULTIMOD)
+	$(MULTIMOD) prerelease -s=true -b=false -v ./versions.yaml -m ${MODSET}
 	$(MAKE) gotidy
 
 COMMIT?=HEAD
 REMOTE?=git@github.com:open-telemetry/opentelemetry-collector.git
 .PHONY: push-tags
-push-tags:
-	$(GO_TOOL) multimod verify
-	set -e; for tag in `$(GO_TOOL) multimod tag -m ${MODSET} -c ${COMMIT} --print-tags | grep -v "Using" `; do \
+push-tags: $(MULTIMOD)
+	$(MULTIMOD) verify
+	set -e; for tag in `$(MULTIMOD) tag -m ${MODSET} -c ${COMMIT} --print-tags | grep -v "Using" `; do \
 		echo "pushing tag $${tag}"; \
 		git push ${REMOTE} $${tag}; \
 	done;
 
 .PHONY: check-changes
-check-changes:
-	$(GO_TOOL) multimod diff -p $(PREVIOUS_VERSION) -m $(MODSET)
+check-changes: $(MULTIMOD)
+	$(MULTIMOD) diff -p $(PREVIOUS_VERSION) -m $(MODSET)
 
 .PHONY: prepare-release
 prepare-release:
@@ -430,29 +429,29 @@ checklinks:
 # error message "failed to sync logger:  sync /dev/stderr: inappropriate ioctl for device"
 # is a known issue but does not affect function.
 .PHONY: crosslink
-crosslink:
+crosslink: $(CROSSLINK)
 	@echo "Executing crosslink"
-	$(GO_TOOL) crosslink --root=$(shell pwd) --prune
+	$(CROSSLINK) --root=$(shell pwd) --prune
 
 FILENAME?=$(shell git branch --show-current)
 .PHONY: chlog-new
-chlog-new:
-	$(GO_TOOL) chloggen new --config $(CHLOGGEN_CONFIG) --filename $(FILENAME)
+chlog-new: $(CHLOGGEN)
+	$(CHLOGGEN) new --config $(CHLOGGEN_CONFIG) --filename $(FILENAME)
 
 .PHONY: chlog-validate
-chlog-validate:
-	$(GO_TOOL) chloggen validate --config $(CHLOGGEN_CONFIG)
+chlog-validate: $(CHLOGGEN)
+	$(CHLOGGEN) validate --config $(CHLOGGEN_CONFIG)
 
 .PHONY: chlog-preview
-chlog-preview:
-	$(GO_TOOL) chloggen update --config $(CHLOGGEN_CONFIG) --dry
+chlog-preview: $(CHLOGGEN)
+	$(CHLOGGEN) update --config $(CHLOGGEN_CONFIG) --dry
 
 .PHONY: chlog-update
-chlog-update:
-	$(GO_TOOL) chloggen update --config $(CHLOGGEN_CONFIG) --version $(VERSION)
+chlog-update: $(CHLOGGEN)
+	$(CHLOGGEN) update --config $(CHLOGGEN_CONFIG) --version $(VERSION)
 
 .PHONY: builder-integration-test
-builder-integration-test:
+builder-integration-test: $(ENVSUBST)
 	cd ./cmd/builder && ./test/test.sh
 
 .PHONY: mdatagen-test
@@ -463,16 +462,16 @@ mdatagen-test:
 	cd cmd/mdatagen && $(GOCMD) test ./...
 
 .PHONY: generate-gh-issue-templates
-generate-gh-issue-templates:
-	$(GO_TOOL) githubgen issue-templates
+generate-gh-issue-templates: $(GITHUBGEN)
+	$(GITHUBGEN) issue-templates
 
 .PHONY: generate-codeowners
-generate-codeowners:
-	$(GO_TOOL) githubgen --default-codeowner "open-telemetry/collector-approvers" codeowners
+generate-codeowners: $(GITHUBGEN)
+	$(GITHUBGEN) --default-codeowner "open-telemetry/collector-approvers" codeowners
 
 .PHONY: gengithub
-gengithub: generate-codeowners generate-gh-issue-templates
+gengithub: $(GITHUBGEN) generate-codeowners generate-gh-issue-templates
 
 .PHONY: gendistributions
-gendistributions:
-	$(GO_TOOL) githubgen distributions
+gendistributions: $(GITHUBGEN)
+	$(GITHUBGEN) distributions
