diff --git a/internal/buildscripts/packaging/fpm/Dockerfile b/internal/buildscripts/packaging/fpm/Dockerfile
deleted file mode 100644
index ec3ff295f..000000000
--- a/internal/buildscripts/packaging/fpm/Dockerfile
+++ /dev/null
@@ -1,16 +0,0 @@
-FROM debian:9
-
-RUN apt-get update && \
-    apt-get install -y ruby ruby-dev rubygems build-essential git rpm
-
-RUN gem install --no-document fpm -v 1.11.0
-
-VOLUME /repo
-WORKDIR /repo
-
-ENV PACKAGE="deb"
-ENV VERSION=""
-ENV ARCH="amd64"
-ENV OUTPUT_DIR="/repo/dist/"
-
-CMD ./internal/buildscripts/packaging/fpm/$PACKAGE/build.sh "$VERSION" "$ARCH" "$OUTPUT_DIR"
\ No newline at end of file
