diff --git a/extension/ballastextension/Makefile b/extension/ballastextension/Makefile
deleted file mode 100644
index ded7a3609..000000000
--- a/extension/ballastextension/Makefile
+++ /dev/null
@@ -1 +0,0 @@
-include ../../Makefile.Common
