diff --git a/Makefile b/Makefile
index 07c5b6adc..c68bcfc7a 100644
--- a/Makefile
+++ b/Makefile
@@ -2,10 +2,8 @@ include ./Makefile.Common
 
 # This is the code that we want to run lint, etc.
 ALL_SRC := $(shell find . -name '*.go' \
-							-not -path './cmd/issuegenerator/*' \
 							-not -path './cmd/mdatagen/*' \
 							-not -path './cmd/schemagen/*' \
-							-not -path './cmd/checkdoc/*' \
 							-not -path './internal/tools/*' \
 							-not -path './examples/demo/app/*' \
 							-not -path './model/internal/data/protogen/*' \
@@ -141,10 +139,10 @@ install-tools:
 	cd $(TOOLS_MOD_DIR) && go install github.com/pavius/impi/cmd/impi
 	cd $(TOOLS_MOD_DIR) && go install github.com/tcnksm/ghr
 	cd $(TOOLS_MOD_DIR) && go install go.opentelemetry.io/build-tools/semconvgen
+	cd $(TOOLS_MOD_DIR) && go install go.opentelemetry.io/build-tools/checkdoc
 	cd $(TOOLS_MOD_DIR) && go install golang.org/x/exp/cmd/apidiff
 	cd $(TOOLS_MOD_DIR) && go install golang.org/x/tools/cmd/goimports
 	cd cmd/mdatagen && go install ./
-	cd cmd/checkdoc && go install ./
 
 .PHONY: otelcol
 otelcol:
@@ -372,7 +370,7 @@ certs-dryrun:
 # Verify existence of READMEs for components specified as default components in the collector.
 .PHONY: checkdoc
 checkdoc:
-	go run cmd/checkdoc/main.go cmd/checkdoc/docs.go --project-path $(CURDIR) --component-rel-path $(COMP_REL_PATH) --module-name $(MOD_NAME)
+	checkdoc --project-path $(CURDIR) --component-rel-path $(COMP_REL_PATH) --module-name $(MOD_NAME)
 
 # Construct new API state snapshots
 .PHONY: apidiff-build
