diff --git a/Makefile b/Makefile
index 181428809..4fe16a4b4 100644
--- a/Makefile
+++ b/Makefile
@@ -20,6 +20,7 @@ TOOLS_MOD_DIR := ./internal/tools
 GOOS=$(shell $(GOCMD) env GOOS)
 GOARCH=$(shell $(GOCMD) env GOARCH)
 
+# TODO: Find a way to configure this in the generated code, currently no effect.
 BUILD_INFO_IMPORT_PATH=go.opentelemetry.io/collector/internal/version
 VERSION=$(shell git describe --always --match "v[0-9]*" HEAD)
 BUILD_INFO=-ldflags "-X $(BUILD_INFO_IMPORT_PATH).Version=$(VERSION)"
