diff --git a/otelcol/otelcoltest/Makefile b/otelcol/otelcoltest/Makefile
new file mode 100644
index 000000000..ded7a3609
--- /dev/null
+++ b/otelcol/otelcoltest/Makefile
@@ -0,0 +1 @@
+include ../../Makefile.Common
