diff --git a/consumer/consumertest/Makefile b/consumer/consumertest/Makefile
new file mode 100644
index 000000000..ded7a3609
--- /dev/null
+++ b/consumer/consumertest/Makefile
@@ -0,0 +1 @@
+include ../../Makefile.Common
