diff --git a/receiver/receivertest/Makefile b/receiver/receivertest/Makefile
new file mode 100644
index 000000000..ded7a3609
--- /dev/null
+++ b/receiver/receivertest/Makefile
@@ -0,0 +1 @@
+include ../../Makefile.Common
