diff --git a/confmap/internal/e2e/Makefile b/confmap/internal/e2e/Makefile
new file mode 100644
index 000000000..bdd863a20
--- /dev/null
+++ b/confmap/internal/e2e/Makefile
@@ -0,0 +1 @@
+include ../../../Makefile.Common
