diff --git a/Makefile b/Makefile
index 2260e9970..b120a887b 100644
--- a/Makefile
+++ b/Makefile
@@ -1,10 +1,17 @@
-ALL_SRC := $(shell find . -type f -name '*.go' -not -path "./vendor/*")
+# More exclusions can be added similar with: -not -path './vendor/*'
+ALL_SRC := $(shell find . -name '*.go' \
+                                -not -path './vendor/*' \
+                                -type f | sort)
+
+# ALL_PKGS is used with 'go cover'
+ALL_PKGS := $(shell go list $(sort $(dir $(ALL_SRC))))
 
 GOTEST_OPT?=-v -race -timeout 30s
 GOTEST_OPT_WITH_COVERAGE = $(GOTEST_OPT) -coverprofile=coverage.txt -covermode=atomic
 GOTEST=go test
 GOFMT=gofmt
 GOLINT=golint
+GOVET=go vet
 GOOS=$(shell go env GOOS)
 
 GIT_SHA=$(shell git rev-parse --short HEAD)
@@ -15,18 +22,32 @@ BUILD_X2=-X $(BUILD_INFO_IMPORT_PATH).Version=$(VERSION)
 endif
 BUILD_INFO=-ldflags "${BUILD_X1} ${BUILD_X2}"
 
-.DEFAULT_GOAL := default_goal
+all_pkgs:
+	@echo $(ALL_PKGS) | tr ' ' '\n' | sort
+
+all_srcs:
+	@echo $(ALL_SRC) | tr ' ' '\n' | sort
 
-.PHONY: default_goal
-default_goal: fmt lint test
+.DEFAULT_GOAL := fmt-vet-lint-test
+
+.PHONY: fmt-vet-lint-test
+fmt-vet-lint-test: fmt vet lint test
 
 .PHONY: test
 test:
-	$(GOTEST) $(GOTEST_OPT) ./...
+	$(GOTEST) $(GOTEST_OPT) $(ALL_PKGS)
+
+.PHONY: travis-ci
+travis-ci: fmt vet lint test-with-cover
 
-.PHONY: test-with-coverage
-test-with-coverage:
-	$(GOTEST) $(GOTEST_OPT_WITH_COVERAGE) ./...
+.PHONY: test-with-cover
+test-with-cover: 
+	@echo Verifying that all packages have test files to count in coverage
+	@scripts/check-test-files.sh $(subst github.com/census-instrumentation/opencensus-service/,./,$(ALL_PKGS))
+	@echo pre-compiling tests
+	@time go test -i $(ALL_PKGS)
+	$(GOTEST) $(GOTEST_OPT_WITH_COVERAGE) $(ALL_PKGS)
+	go tool cover -html=coverage.txt -o coverage.html
 
 .PHONY: fmt
 fmt:
@@ -35,15 +56,30 @@ fmt:
 		echo "$(GOFMT) FAILED => gofmt the following files:\n"; \
 		echo "$$FMTOUT\n"; \
 		exit 1; \
+	else \
+	    echo "Fmt finished successfully"; \
 	fi
 
 .PHONY: lint
 lint:
-	@LINTOUT=`$(GOLINT) ./... 2>&1`; \
+	@LINTOUT=`$(GOLINT) $(ALL_PKGS) 2>&1`; \
 	if [ "$$LINTOUT" ]; then \
 		echo "$(GOLINT) FAILED => clean the following lint errors:\n"; \
 		echo "$$LINTOUT\n"; \
 		exit 1; \
+	else \
+	    echo "Lint finished successfully"; \
+	fi
+
+.PHONY: vet
+vet:
+	@VETOUT=`$(GOVET) ./... 2>&1`; \
+	if [ "$$VETOUT" ]; then \
+		echo "$(GOVET) FAILED => clean the following vet errors:\n"; \
+		echo "$$VETOUT\n"; \
+		exit 1; \
+	else \
+	    echo "Vet finished successfully"; \
 	fi
 
 .PHONY: install-tools
