diff --git a/component/componentprofiles/Makefile b/component/componentprofiles/Makefile
deleted file mode 100644
index ded7a3609..000000000
--- a/component/componentprofiles/Makefile
+++ /dev/null
@@ -1 +0,0 @@
-include ../../Makefile.Common
