diff --git a/Makefile b/Makefile
index 394168d0b..f9deb2e04 100644
--- a/Makefile
+++ b/Makefile
@@ -198,7 +198,7 @@ otelcorecol:
 
 .PHONY: genotelcorecol
 genotelcorecol:
-	pushd cmd/builder/ && go run ./ --config ../otelcorecol/builder-config.yaml --output-path ../otelcorecol --skip-compilation && popd
+	pushd cmd/builder/ && go run ./ --skip-compilation --config ../otelcorecol/builder-config.yaml --output-path ../otelcorecol && popd
 
 .PHONY: genmdata
 genmdata:
