diff --git a/internal/testutil/Makefile b/internal/testutil/Makefile
new file mode 100644
index 000000000..ded7a3609
--- /dev/null
+++ b/internal/testutil/Makefile
@@ -0,0 +1 @@
+include ../../Makefile.Common
