diff --git a/consumer/consumererror/consumererrorprofiles/Makefile b/consumer/consumererror/consumererrorprofiles/Makefile
deleted file mode 100644
index bdd863a20..000000000
--- a/consumer/consumererror/consumererrorprofiles/Makefile
+++ /dev/null
@@ -1 +0,0 @@
-include ../../../Makefile.Common
