diff --git a/Makefile b/Makefile
index 556e6a25d..bc70f1da1 100644
--- a/Makefile
+++ b/Makefile
@@ -14,6 +14,7 @@ GOTEST_OPT?= -race -timeout 30s
 GOTEST_OPT_WITH_COVERAGE = $(GOTEST_OPT) -coverprofile=coverage.txt -covermode=atomic
 GOTEST=go test
 GOOS=$(shell go env GOOS)
+GOARCH=$(shell go env GOARCH)
 ADDLICENCESE= addlicense
 MISSPELL=misspell -error
 MISSPELL_CORRECTION=misspell -w
@@ -54,7 +55,7 @@ benchmark:
 	$(GOTEST) -bench=. -run=notests $(ALL_PKGS)
 
 .PHONY: ci
-ci: all test-with-cover
+ci: all binaries-all-sys test-with-cover
 	$(MAKE) -C testbed install-tools
 	$(MAKE) -C testbed runtests
 
@@ -125,12 +126,12 @@ install-tools:
 
 .PHONY: otelcol
 otelcol:
-	GO111MODULE=on CGO_ENABLED=0 go build -o ./bin/$(GOOS)/otelcol $(BUILD_INFO) ./cmd/otelcol
+	GO111MODULE=on CGO_ENABLED=0 go build -o ./bin/$(GOOS)_$(GOARCH)/otelcol $(BUILD_INFO) ./cmd/otelcol
 
 .PHONY: docker-component # Not intended to be used directly
 docker-component: check-component
 	GOOS=linux $(MAKE) $(COMPONENT)
-	cp ./bin/linux/$(COMPONENT) ./cmd/$(COMPONENT)/
+	cp ./bin/linux_amd64/$(COMPONENT) ./cmd/$(COMPONENT)/
 	docker build -t $(COMPONENT) ./cmd/$(COMPONENT)/
 	rm ./cmd/$(COMPONENT)/$(COMPONENT)
 
@@ -149,6 +150,7 @@ binaries: otelcol
 
 .PHONY: binaries-all-sys
 binaries-all-sys:
-	GOOS=darwin $(MAKE) binaries
-	GOOS=linux $(MAKE) binaries
-	GOOS=windows $(MAKE) binaries
+	GOOS=darwin GOARCH=amd64 $(MAKE) binaries
+	GOOS=linux GOARCH=amd64 $(MAKE) binaries
+	GOOS=linux GOARCH=arm64 $(MAKE) binaries
+	GOOS=windows GOARCH=amd64 $(MAKE) binaries
