diff --git a/Makefile b/Makefile
index ca38775e7..11bb523df 100644
--- a/Makefile
+++ b/Makefile
@@ -1,6 +1,6 @@
 ALL_SRC := $(shell find . -type f -name '*.go' -not -path "./vendor/*")
 
-GOTEST_OPT?=-v -race
+GOTEST_OPT?=-v -race -timeout 30s
 GOTEST=go test
 GOFMT=gofmt
 GOLINT=golint
