diff --git a/Makefile b/Makefile
index e076774a0..e7d397b73 100644
--- a/Makefile
+++ b/Makefile
@@ -71,6 +71,10 @@ gotest-with-cover:
 	@$(MAKE) for-all CMD="make test-with-cover"
 	$(GOCOVMERGE) $$(find . -name coverage.out) > coverage.txt
 
+.PHONY: goporto
+goporto:
+	@$(MAKE) for-all CMD="make porto"
+
 .PHONY: golint
 golint:
 	@$(MAKE) for-all CMD="make lint lint-unstable"
@@ -134,6 +138,7 @@ install-tools:
 	cd $(TOOLS_MOD_DIR) && go install go.opentelemetry.io/build-tools/semconvgen
 	cd $(TOOLS_MOD_DIR) && go install golang.org/x/exp/cmd/apidiff
 	cd $(TOOLS_MOD_DIR) && go install golang.org/x/tools/cmd/goimports
+	cd $(TOOLS_MOD_DIR) && go install github.com/jcchavezs/porto/cmd/porto
 
 .PHONY: otelcol
 otelcol:
