diff --git a/cmd/otelcorecol/Makefile b/cmd/otelcorecol/Makefile
new file mode 100644
index 000000000..ded7a3609
--- /dev/null
+++ b/cmd/otelcorecol/Makefile
@@ -0,0 +1 @@
+include ../../Makefile.Common
