diff --git a/config/configauth/Makefile b/config/configauth/Makefile
new file mode 100644
index 000000000..ded7a3609
--- /dev/null
+++ b/config/configauth/Makefile
@@ -0,0 +1 @@
+include ../../Makefile.Common
