diff --git a/Makefile b/Makefile
index dd3ce1e67..cca56b17c 100644
--- a/Makefile
+++ b/Makefile
@@ -273,6 +273,12 @@ build-binary-internal-unstable:
 	docker build -t otelcol-fpm internal/buildscripts/packaging/fpm
 	docker run --rm -v $(CURDIR):/repo -e PACKAGE=$* -e VERSION=$(VERSION) -e ARCH=$(ARCH) otelcol-fpm
 
+# Builds a collector binary of the removed cmd/otelcol directory
+.PHONY: build-binary-cmd-otelcol
+build-binary-cmd-otelcol:
+	mkdir -p ./bin
+	pushd cmd/builder/ && go run ./ --config ../../internal/buildscripts/builder-config.yaml --output-path ../../bin && popd
+
 .PHONY: genmdata
 genmdata:
 	$(MAKE) for-all CMD="go generate ./..."
