diff --git a/exporter/exporterprofiles/Makefile b/exporter/exporterprofiles/Makefile
new file mode 100644
index 000000000..ded7a3609
--- /dev/null
+++ b/exporter/exporterprofiles/Makefile
@@ -0,0 +1 @@
+include ../../Makefile.Common
