diff --git a/Makefile b/Makefile
index 33ad6d40a..06bf3db25 100644
--- a/Makefile
+++ b/Makefile
@@ -1,6 +1,6 @@
 ALL_SRC := $(shell find . -type f -name '*.go' -not -path "./vendor/*")
 
-GOTEST_OPT=-v -race
+GOTEST_OPT?=-v -race
 GOTEST=go test
 GOFMT=gofmt
 GOOS=$(shell go env GOOS)
@@ -14,10 +14,6 @@ BUILD_INFO=-ldflags "-X $(BUILD_INFO_IMPORT_PATH).GitHash=$(GIT_SHA)"
 .PHONY: default_goal
 default_goal: fmt test
 
-.PHONY: clean
-clean:
-	rm -rf bin/ 
-
 .PHONY: test
 test:
 	$(GOTEST) $(GOTEST_OPT) ./...
@@ -39,6 +35,28 @@ agent:
 collector:
 	CGO_ENABLED=0 go build -o ./bin/occollector_$(GOOS) $(BUILD_INFO) ./cmd/occollector
 
+.PHONY: docker-component # Not intended to be used directly
+docker-component: check-component
+	GOOS=linux $(MAKE) $(COMPONENT)
+	cp ./bin/oc$(COMPONENT)_linux ./cmd/oc$(COMPONENT)/
+	docker build -t oc$(COMPONENT) ./cmd/oc$(COMPONENT)/
+	rm ./cmd/oc$(COMPONENT)/oc$(COMPONENT)_linux
+
+.PHONY: check-component
+check-component:
+ifndef COMPONENT
+	$(error COMPONENT variable was not defined)
+endif
+
+.PHONY: docker-agent
+docker-agent:
+	COMPONENT=agent $(MAKE) docker-component
+
+.PHONY: docker-collector
+docker-collector: 
+	COMPONENT=collector $(MAKE) docker-component
+
+
 .PHONY: binaries
 binaries: agent collector
 
