diff --git a/Makefile b/Makefile
index ef0e50d0a..b03c4a1b9 100644
--- a/Makefile
+++ b/Makefile
@@ -162,7 +162,7 @@ otelcol:
 
 .PHONY: run
 run:
-	GO111MODULE=on go run --race ./cmd/otelcol/... --config ${RUN_CONFIG}
+	GO111MODULE=on go run --race ./cmd/otelcol/... --config ${RUN_CONFIG} ${RUN_ARGS}
 
 .PHONY: docker-component # Not intended to be used directly
 docker-component: check-component
