diff --git a/confmap/provider/httpprovider/Makefile b/confmap/provider/httpprovider/Makefile
new file mode 100644
index 000000000..bdd863a20
--- /dev/null
+++ b/confmap/provider/httpprovider/Makefile
@@ -0,0 +1 @@
+include ../../../Makefile.Common
