diff --git a/connector/connectorprofiles/Makefile b/connector/connectorprofiles/Makefile
new file mode 100644
index 000000000..ded7a3609
--- /dev/null
+++ b/connector/connectorprofiles/Makefile
@@ -0,0 +1 @@
+include ../../Makefile.Common
