diff --git a/Makefile b/Makefile
index 7df62f585..b2c3714b5 100644
--- a/Makefile
+++ b/Makefile
@@ -39,7 +39,7 @@ endif
 BUILD_X3=-X $(BUILD_INFO_IMPORT_PATH).BuildType=$(BUILD_TYPE)
 BUILD_INFO=-ldflags "${BUILD_X1} ${BUILD_X2} ${BUILD_X3}"
 
-RUN_CONFIG?=examples/otel-local-config.yaml
+RUN_CONFIG?=examples/local/otel-config.yaml
 
 CONTRIB_PATH=$(CURDIR)/../opentelemetry-collector-contrib
 
