diff --git a/consumer/consumererror/xconsumererror/Makefile b/consumer/consumererror/xconsumererror/Makefile
new file mode 100644
index 000000000..bdd863a20
--- /dev/null
+++ b/consumer/consumererror/xconsumererror/Makefile
@@ -0,0 +1 @@
+include ../../../Makefile.Common
