diff --git a/confmap/converter/expandconverter/Makefile b/confmap/converter/expandconverter/Makefile
deleted file mode 100644
index bdd863a20..000000000
--- a/confmap/converter/expandconverter/Makefile
+++ /dev/null
@@ -1 +0,0 @@
-include ../../../Makefile.Common
