diff --git a/exporter/loggingexporter/Makefile b/exporter/loggingexporter/Makefile
deleted file mode 100644
index ded7a3609..000000000
--- a/exporter/loggingexporter/Makefile
+++ /dev/null
@@ -1 +0,0 @@
-include ../../Makefile.Common
