diff --git a/processor/processorprofiles/Makefile b/processor/processorprofiles/Makefile
deleted file mode 100644
index ded7a3609..000000000
--- a/processor/processorprofiles/Makefile
+++ /dev/null
@@ -1 +0,0 @@
-include ../../Makefile.Common
