diff --git a/pdata/testdata/Makefile b/pdata/testdata/Makefile
new file mode 100644
index 000000000..ded7a3609
--- /dev/null
+++ b/pdata/testdata/Makefile
@@ -0,0 +1 @@
+include ../../Makefile.Common
