diff --git a/Makefile b/Makefile
index aff773447..a10af44b2 100644
--- a/Makefile
+++ b/Makefile
@@ -261,10 +261,8 @@ gensemconv: $(SEMCONVGEN) $(SEMCONVKIT)
 
 ALL_MOD_PATHS := "" $(ALL_MODULES:.%=%)
 
-# Checks that the HEAD of the contrib repo checked out in CONTRIB_PATH compiles
-# against the current version of this repo.
-.PHONY: check-contrib
-check-contrib:
+.PHONY: prepare-contrib
+prepare-contrib:
 	@echo Setting contrib at $(CONTRIB_PATH) to use this core checkout
 	@$(MAKE) -j2 -C $(CONTRIB_PATH) for-all CMD="$(GOCMD) mod edit \
 		$(addprefix -replace ,$(join $(ALL_MOD_PATHS:%=go.opentelemetry.io/collector%=),$(ALL_MOD_PATHS:%=$(CURDIR)%)))"
@@ -272,6 +270,10 @@ check-contrib:
 
 	@$(MAKE) generate-contrib
 
+# Checks that the HEAD of the contrib repo checked out in CONTRIB_PATH compiles
+# against the current version of this repo.
+.PHONY: check-contrib
+check-contrib:
 	@echo -e "\nRunning tests"
 	@$(MAKE) -C $(CONTRIB_PATH) gotest
 
