diff --git a/cmd/otelcol/Dockerfile b/cmd/otelcol/Dockerfile
index 1ed6bac92..2db540d26 100644
--- a/cmd/otelcol/Dockerfile
+++ b/cmd/otelcol/Dockerfile
@@ -1,6 +1,5 @@
 FROM alpine:3.12 as certs
 RUN apk --update add ca-certificates
-RUN mkdir -m 777 /scratchtmp
 
 FROM alpine:3.12 AS otelcol
 COPY otelcol /
@@ -9,9 +8,6 @@ COPY otelcol /
 RUN chmod 755 /otelcol
 
 FROM scratch
-# Make an empty /tmp directory as the Kubernetes client-go library tries to log to here.
-# If it is unable to do so, it causes the collector to exit (see issue #587).
-COPY --from=certs /scratchtmp /tmp
 COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
 COPY --from=otelcol /otelcol /
 ENTRYPOINT ["/otelcol"]
