diff --git a/receiver/receiverhelper/Makefile b/receiver/receiverhelper/Makefile
new file mode 100644
index 000000000..ded7a3609
--- /dev/null
+++ b/receiver/receiverhelper/Makefile
@@ -0,0 +1 @@
+include ../../Makefile.Common
