diff --git a/Makefile b/Makefile
index 7bd3f5559..e37c74290 100644
--- a/Makefile
+++ b/Makefile
@@ -250,7 +250,7 @@ genpdata:
 	pushd pdata/ && $(GOCMD) run ./internal/cmd/pdatagen/main.go && popd
 	$(MAKE) fmt
 
-INTERNAL_PROTO_SRC_DIRS := exporter/exporterhelper/internal/queuebatch/internal/persistentqueue
+INTERNAL_PROTO_SRC_DIRS := exporter/exporterhelper/internal/queue
 # INTERNAL_PROTO_SRC_DIRS += path/to/other/proto/dirs
 INTERNAL_PROTO_FILES := $(foreach dir,$(INTERNAL_PROTO_SRC_DIRS),$(wildcard $(dir)/*.proto))
 INTERNAL_PROTOC := $(DOCKERCMD) run --rm -u ${shell id -u} -v${PWD}:${PWD} -w${PWD} ${DOCKER_PROTOBUF} --proto_path=${PWD} --go_out=${PWD}
