diff --git a/extension/experimental/storage/Makefile b/extension/experimental/storage/Makefile
index ded7a3609..bdd863a20 100644
--- a/extension/experimental/storage/Makefile
+++ b/extension/experimental/storage/Makefile
@@ -1 +1 @@
-include ../../Makefile.Common
+include ../../../Makefile.Common
