diff --git a/cmd/configschema/Makefile b/cmd/configschema/Makefile
deleted file mode 100644
index ded7a3609..000000000
--- a/cmd/configschema/Makefile
+++ /dev/null
@@ -1 +0,0 @@
-include ../../Makefile.Common
