diff --git a/extension/extensionmiddleware/Makefile b/extension/extensionmiddleware/Makefile
new file mode 100644
index 000000000..ded7a3609
--- /dev/null
+++ b/extension/extensionmiddleware/Makefile
@@ -0,0 +1 @@
+include ../../Makefile.Common
