diff --git a/Makefile b/Makefile
index 5852e93b7..192f15aa3 100644
--- a/Makefile
+++ b/Makefile
@@ -55,16 +55,22 @@ all-pkgs:
 .PHONY: all
 all: checklicense impi lint misspell test otelcol
 
-.PHONY: testbed-runtests
-testbed-runtests: otelcol
-	cd ./testbed/correctness && ./runtests.sh
+.PHONY: testbed-loadtest
+testbed-loadtest: otelcol
 	cd ./testbed/tests && ./runtests.sh
 
-.PHONY: testbed-listtests
-testbed-listtests:
-	TESTBED_CONFIG=inprocess.yaml $(GOTEST) -v ./testbed/correctness --test.list '.*'|head -n 10
+.PHONY: testbed-correctness
+testbed-correctness: otelcol
+	cd ./testbed/correctness && ./runtests.sh
+
+.PHONY: testbed-list-loadtest
+testbed-list-loadtest:
 	TESTBED_CONFIG=local.yaml $(GOTEST) -v ./testbed/tests --test.list '.*'|head -n 20
 
+.PHONY: testbed-list-correctness
+testbed-list-correctness:
+	TESTBED_CONFIG=inprocess.yaml $(GOTEST) -v ./testbed/correctness --test.list '.*'|head -n 10
+
 .PHONY: test
 test:
 	echo $(ALL_PKGS) | xargs -n 10 $(GOTEST) $(GOTEST_OPT)
