diff --git a/cmd/schemagen/Makefile b/cmd/schemagen/Makefile
deleted file mode 100644
index ded7a3609..000000000
--- a/cmd/schemagen/Makefile
+++ /dev/null
@@ -1 +0,0 @@
-include ../../Makefile.Common
