diff --git a/Makefile b/Makefile
index b3c8525ca..10a4293c7 100644
--- a/Makefile
+++ b/Makefile
@@ -269,7 +269,7 @@ PROTO_PACKAGE=go.opentelemetry.io/collector/$(PROTO_TARGET_GEN_DIR)
 # Intermediate directory used during generation.
 PROTO_INTERMEDIATE_DIR=internal/data/.patched-otlp-proto
 
-DOCKER_PROTOBUF ?= otel/build-protobuf:0.1.0
+DOCKER_PROTOBUF ?= otel/build-protobuf:0.2.1
 PROTOC := docker run --rm -u ${shell id -u} -v${PWD}:${PWD} -w${PWD}/$(PROTO_INTERMEDIATE_DIR) ${DOCKER_PROTOBUF} --proto_path=${PWD}
 PROTO_INCLUDES := -I/usr/include/github.com/gogo/protobuf -I./
 
