diff --git a/processor/batchprocessor/Makefile b/processor/batchprocessor/Makefile
new file mode 100644
index 000000000..ded7a3609
--- /dev/null
+++ b/processor/batchprocessor/Makefile
@@ -0,0 +1 @@
+include ../../Makefile.Common
