diff --git a/Makefile b/Makefile
index 5e7c75c8c..2a4d766ff 100644
--- a/Makefile
+++ b/Makefile
@@ -362,3 +362,4 @@ multimod-verify: install-tools
 .PHONY: multimod-prerelease
 multimod-prerelease: install-tools
 	multimod prerelease -v ./versions.yaml -m collector-base
+	$(MAKE) gotidy
