diff --git a/examples/demo/server/Makefile b/examples/demo/server/Makefile
deleted file mode 100644
index bdd863a20..000000000
--- a/examples/demo/server/Makefile
+++ /dev/null
@@ -1 +0,0 @@
-include ../../../Makefile.Common
