diff --git a/Makefile b/Makefile
index a6da8a3f5..94daa2ea4 100644
--- a/Makefile
+++ b/Makefile
@@ -26,7 +26,7 @@ GOOS=$(shell go env GOOS)
 GOARCH=$(shell go env GOARCH)
 
 BUILD_INFO_IMPORT_PATH=go.opentelemetry.io/collector/internal/version
-VERSION=$(shell git describe --match "v[0-9]*" HEAD)
+VERSION=$(shell git describe --always --match "v[0-9]*" HEAD)
 BUILD_INFO=-ldflags "-X $(BUILD_INFO_IMPORT_PATH).Version=$(VERSION)"
 
 RUN_CONFIG?=examples/local/otel-config.yaml
@@ -49,6 +49,10 @@ endef
 
 .DEFAULT_GOAL := all
 
+.PHONY: version
+version:
+	@echo ${VERSION}
+
 .PHONY: all
 all: checklicense checkdoc misspell goimpi golint gotest otelcol
 
@@ -251,7 +255,6 @@ binaries-windows_amd64:
 build-binary-internal:
 	GO111MODULE=on CGO_ENABLED=0 go build -trimpath -o ./bin/otelcol_$(GOOS)_$(GOARCH)$(EXTENSION) $(BUILD_INFO) ./cmd/otelcol
 
-
 .PHONY: deb-rpm-package
 %-package: ARCH ?= amd64
 %-package:
