diff --git a/Makefile b/Makefile
index b6f7fc132..fb2b06c36 100644
--- a/Makefile
+++ b/Makefile
@@ -315,6 +315,10 @@ certs:
 certs-dryrun:
 	@internal/buildscripts/gen-certs.sh -d
 
+.PHONY: checkapi
+checkapi: $(CHECKAPI)
+	$(CHECKAPI) -folder . -config .checkapi.yaml
+
 # Verify existence of READMEs for components specified as default components in the collector.
 .PHONY: checkdoc
 checkdoc: $(CHECKFILE)
