diff --git a/extension/auth/authtest/Makefile b/extension/auth/authtest/Makefile
deleted file mode 100644
index bdd863a20..000000000
--- a/extension/auth/authtest/Makefile
+++ /dev/null
@@ -1 +0,0 @@
-include ../../../Makefile.Common
