diff --git a/Makefile b/Makefile
index 55c03e8bc..97c806bfa 100644
--- a/Makefile
+++ b/Makefile
@@ -445,3 +445,18 @@ mdatagen-test:
 	cd cmd/mdatagen && $(GOCMD) install .
 	cd cmd/mdatagen && $(GOCMD) generate ./...
 	cd cmd/mdatagen && $(GOCMD) test ./...
+
+.PHONY: generate-gh-issue-templates
+generate-gh-issue-templates: $(GITHUBGEN)
+	$(GITHUBGEN) issue-templates
+
+.PHONY: generate-codeowners
+generate-codeowners: $(GITHUBGEN)
+	$(GITHUBGEN) --default-codeowner "open-telemetry/collector-approvers" codeowners
+
+.PHONY: gengithub
+gengithub: $(GITHUBGEN) generate-codeowners generate-gh-issue-templates
+
+.PHONY: gendistributions
+gendistributions: $(GITHUBGEN)
+	$(GITHUBGEN) distributions
