diff --git a/cmd/otelcol/Dockerfile b/cmd/otelcol/Dockerfile
index e173eb64d..edc952e8a 100644
--- a/cmd/otelcol/Dockerfile
+++ b/cmd/otelcol/Dockerfile
@@ -1,7 +1,11 @@
 FROM alpine:3.9 as certs
 RUN apk --update add ca-certificates
+RUN mkdir -m 777 /scratchtmp
 
 FROM scratch
+# Make an empty /tmp directory as the Kubernetes client-go library tries to log to here.
+# If it is unable to do so, it causes the collector to exit (see issue #587).
+COPY --from=certs /scratchtmp /tmp
 COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
 COPY otelcol /
 ENTRYPOINT ["/otelcol"]
