diff --git a/confmap/converter/expandconverter/Makefile b/confmap/converter/expandconverter/Makefile
new file mode 100644
index 000000000..bdd863a20
--- /dev/null
+++ b/confmap/converter/expandconverter/Makefile
@@ -0,0 +1 @@
+include ../../../Makefile.Common
