diff --git a/Makefile b/Makefile
index bd97f55e6..53ce92e52 100644
--- a/Makefile
+++ b/Makefile
@@ -174,6 +174,7 @@ otelcorecol:
 .PHONY: genotelcorecol
 genotelcorecol:
 	pushd cmd/builder/ && $(GOCMD) run ./ --skip-compilation --config ../otelcorecol/builder-config.yaml --output-path ../otelcorecol && popd
+	$(MAKE) -C cmd/otelcorecol fmt
 
 .PHONY: ocb
 ocb:
