diff --git a/cmd/otelcol/Dockerfile b/cmd/otelcol/Dockerfile
new file mode 100644
index 000000000..e173eb64d
--- /dev/null
+++ b/cmd/otelcol/Dockerfile
@@ -0,0 +1,8 @@
+FROM alpine:3.9 as certs
+RUN apk --update add ca-certificates
+
+FROM scratch
+COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
+COPY otelcol /
+ENTRYPOINT ["/otelcol"]
+EXPOSE 55678 55679
