diff --git a/Makefile b/Makefile
index 6042470f1..db1c4c911 100644
--- a/Makefile
+++ b/Makefile
@@ -64,15 +64,15 @@ gotest-with-cover: $(GOCOVMERGE)
 	$(GOCOVMERGE) $$(find . -name coverage.out) > coverage.txt
 
 .PHONY: goporto
-goporto: install-tools
-	porto -w --include-internal ./
+goporto: $(PORTO)
+	$(PORTO) -w --include-internal ./
 
 .PHONY: golint
 golint:
 	@$(MAKE) for-all-target TARGET="lint"
 
 .PHONY: goimpi
-goimpi: install-tools
+goimpi:
 	@$(MAKE) for-all-target TARGET="impi"
 
 .PHONY: gofmt
@@ -334,8 +334,8 @@ certs-dryrun:
 
 # Verify existence of READMEs for components specified as default components in the collector.
 .PHONY: checkdoc
-checkdoc:
-	checkdoc --project-path $(CURDIR) --component-rel-path $(COMP_REL_PATH) --module-name $(MOD_NAME)
+checkdoc: $(CHECKDOC)
+	$(CHECKDOC) --project-path $(CURDIR) --component-rel-path $(COMP_REL_PATH) --module-name $(MOD_NAME)
 
 # Construct new API state snapshots
 .PHONY: apidiff-build
