diff --git a/exporter/exporterhelper/exporterhelperprofiles/Makefile b/exporter/exporterhelper/exporterhelperprofiles/Makefile
deleted file mode 100644
index bdd863a20..000000000
--- a/exporter/exporterhelper/exporterhelperprofiles/Makefile
+++ /dev/null
@@ -1 +0,0 @@
-include ../../../Makefile.Common
