diff --git a/confmap/xconfmap/Makefile b/confmap/xconfmap/Makefile
new file mode 100644
index 000000000..ded7a3609
--- /dev/null
+++ b/confmap/xconfmap/Makefile
@@ -0,0 +1 @@
+include ../../Makefile.Common
