diff --git a/internal/sharedcomponent/Makefile b/internal/sharedcomponent/Makefile
new file mode 100644
index 000000000..ded7a3609
--- /dev/null
+++ b/internal/sharedcomponent/Makefile
@@ -0,0 +1 @@
+include ../../Makefile.Common
