diff --git a/component/componenttest/Makefile b/component/componenttest/Makefile
new file mode 100644
index 000000000..ded7a3609
--- /dev/null
+++ b/component/componenttest/Makefile
@@ -0,0 +1 @@
+include ../../Makefile.Common
