diff --git a/exporter/exportertest/Makefile b/exporter/exportertest/Makefile
new file mode 100644
index 000000000..c1496226e
--- /dev/null
+++ b/exporter/exportertest/Makefile
@@ -0,0 +1 @@
+include ../../Makefile.Common
\ No newline at end of file
