diff --git a/processor/processorhelper/xprocessorhelper/Makefile b/processor/processorhelper/xprocessorhelper/Makefile
new file mode 100644
index 000000000..bdd863a20
--- /dev/null
+++ b/processor/processorhelper/xprocessorhelper/Makefile
@@ -0,0 +1 @@
+include ../../../Makefile.Common
