diff --git a/Makefile b/Makefile
index 60ee82a76..e05b32e53 100644
--- a/Makefile
+++ b/Makefile
@@ -60,6 +60,16 @@ gotest-with-cover:
 goporto: $(PORTO)
 	$(PORTO) -w --include-internal --skip-dirs "^cmd/mdatagen/third_party$$" ./
 
+.PHONY: for-all
+for-all:
+	@echo "running $${CMD} in root"
+	@$${CMD}
+	@set -e; for dir in $(GOMODULES); do \
+	  (cd "$${dir}" && \
+	  	echo "running $${CMD} in $${dir}" && \
+	 	$${CMD} ); \
+	done
+
 .PHONY: golint
 golint:
 	@$(MAKE) for-all-target TARGET="lint"
