diff --git a/extension/zpagesextension/Makefile b/extension/zpagesextension/Makefile
new file mode 100644
index 000000000..ded7a3609
--- /dev/null
+++ b/extension/zpagesextension/Makefile
@@ -0,0 +1 @@
+include ../../Makefile.Common
