diff --git a/Makefile b/Makefile
index ce45dcf18..f167a42d6 100644
--- a/Makefile
+++ b/Makefile
@@ -1,6 +1,7 @@
 # More exclusions can be added similar with: -not -path './vendor/*'
 ALL_SRC := $(shell find . -name '*.go' \
                                 -not -path './vendor/*' \
+                                -not -path './testbed/*' \
                                 -not -path './tools/*' \
                                 -type f | sort)
 
@@ -34,6 +35,10 @@ all-srcs:
 .PHONY: fmt-vet-lint-test
 fmt-vet-lint-test: fmt vet lint test
 
+.PHONY: perf-test
+perf-test: otelsvc
+	$(MAKE) -C testbed runtests
+
 .PHONY: test
 test:
 	$(GOTEST) $(GOTEST_OPT) $(ALL_PKGS)
