diff --git a/Makefile b/Makefile
index e87808ce6..1cdb58b4d 100644
--- a/Makefile
+++ b/Makefile
@@ -467,7 +467,7 @@ generate-gh-issue-templates: $(GITHUBGEN)
 
 .PHONY: generate-codeowners
 generate-codeowners: $(GITHUBGEN)
-	$(GITHUBGEN) --default-codeowner "open-telemetry/collector-approvers" codeowners
+	$(GITHUBGEN) --default-codeowner "open-telemetry/collector-approvers" -skipgithub codeowners
 
 .PHONY: gengithub
 gengithub: $(GITHUBGEN) generate-codeowners generate-gh-issue-templates
