diff --git a/connector/forwardconnector/Makefile b/connector/forwardconnector/Makefile
new file mode 100644
index 000000000..ded7a3609
--- /dev/null
+++ b/connector/forwardconnector/Makefile
@@ -0,0 +1 @@
+include ../../Makefile.Common
