diff --git a/Makefile b/Makefile
index 76c526ca1..3b8e0e057 100644
--- a/Makefile
+++ b/Makefile
@@ -33,10 +33,7 @@ GIT_SHA=$(shell git rev-parse --short HEAD)
 BUILD_X1=-X $(BUILD_INFO_IMPORT_PATH).GitHash=$(GIT_SHA)
 VERSION=$(shell git describe --match "v[0-9]*" HEAD)
 BUILD_X2=-X $(BUILD_INFO_IMPORT_PATH).Version=$(VERSION)
-# BUILD_TYPE should be one of (dev, release).
-BUILD_TYPE?=release
-BUILD_X3=-X $(BUILD_INFO_IMPORT_PATH).BuildType=$(BUILD_TYPE)
-BUILD_INFO=-ldflags "${BUILD_X1} ${BUILD_X2} ${BUILD_X3}"
+BUILD_INFO=-ldflags "${BUILD_X1} ${BUILD_X2}"
 
 RUN_CONFIG?=examples/local/otel-config.yaml
 
