diff --git a/consumer/consumerprofiles/Makefile b/consumer/consumerprofiles/Makefile
deleted file mode 100644
index ded7a3609..000000000
--- a/consumer/consumerprofiles/Makefile
+++ /dev/null
@@ -1 +0,0 @@
-include ../../Makefile.Common
