diff --git a/pipeline/xpipeline/Makefile b/pipeline/xpipeline/Makefile
new file mode 100644
index 000000000..ded7a3609
--- /dev/null
+++ b/pipeline/xpipeline/Makefile
@@ -0,0 +1 @@
+include ../../Makefile.Common
