diff --git a/testbed/Makefile b/testbed/Makefile
index 688b37581..9d94b3c84 100644
--- a/testbed/Makefile
+++ b/testbed/Makefile
@@ -21,14 +21,7 @@ runtests: test
 
 .PHONY: fmt
 fmt:
-	@FMTOUT=`$(GOFMT) -s -l ./.. 2>&1`; \
-	if [ "$$FMTOUT" ]; then \
-		echo "$(GOFMT) FAILED => gofmt the following files:\n"; \
-		echo "$$FMTOUT\n"; \
-		exit 1; \
-	else \
-	    echo "Fmt finished successfully"; \
-	fi
+	$(GOFMT) -s -l ./..
 
 .PHONY: lint
 lint:
