diff --git a/receiver/receiverprofiles/Makefile b/receiver/receiverprofiles/Makefile
deleted file mode 100644
index ded7a3609..000000000
--- a/receiver/receiverprofiles/Makefile
+++ /dev/null
@@ -1 +0,0 @@
-include ../../Makefile.Common
