diff --git a/cmd/otelsvc/Dockerfile b/cmd/otelsvc/Dockerfile
new file mode 100644
index 000000000..118a69baa
--- /dev/null
+++ b/cmd/otelsvc/Dockerfile
@@ -0,0 +1,8 @@
+FROM alpine:3.9 as certs
+RUN apk --update add ca-certificates
+
+FROM scratch
+COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
+COPY otelsvc_linux /
+ENTRYPOINT ["/otelsvc_linux"]
+EXPOSE 55678 55679
