diff --git a/Makefile b/Makefile
index e2c90859e..9898cc679 100644
--- a/Makefile
+++ b/Makefile
@@ -25,7 +25,6 @@ MISSPELL=misspell -error
 MISSPELL_CORRECTION=misspell -w
 LINT=golangci-lint
 IMPI=impi
-GOSEC=gosec
 STATIC_CHECK=staticcheck
 # BUILD_TYPE should be one of (dev, release).
 BUILD_TYPE?=release
@@ -119,11 +118,6 @@ misspell:
 misspell-correction:
 	$(MISSPELL_CORRECTION) $(ALL_DOC)
 
-.PHONY: lint-gosec
-lint-gosec:
-	# TODO: Consider to use gosec from golangci-lint
-	$(GOSEC) -quiet -exclude=G104 $(ALL_PKGS)
-
 .PHONY: lint-static-check
 lint-static-check:
 	@STATIC_CHECK_OUT=`$(STATIC_CHECK) $(ALL_PKGS) 2>&1`; \
@@ -157,7 +151,6 @@ install-tools:
 	go install github.com/mjibson/esc
 	go install github.com/ory/go-acc
 	go install github.com/pavius/impi/cmd/impi
-	go install github.com/securego/gosec/cmd/gosec
 	go install github.com/tcnksm/ghr
 	go install golang.org/x/tools/cmd/goimports
 	go install honnef.co/go/tools/cmd/staticcheck
