diff --git a/cmd/occollector/Dockerfile b/cmd/occollector/Dockerfile
index 1eeaa2903..cbba7f949 100644
--- a/cmd/occollector/Dockerfile
+++ b/cmd/occollector/Dockerfile
@@ -1,4 +1,8 @@
+FROM alpine:latest as certs
+RUN apk --update add ca-certificates
+
 FROM scratch
+COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
 COPY occollector_linux /
 ENTRYPOINT ["/occollector_linux"]
 EXPOSE 55678
