diff --git a/Makefile b/Makefile
index e217db031..abd49f220 100644
--- a/Makefile
+++ b/Makefile
@@ -94,7 +94,8 @@ gofmt:
 .PHONY: gotidy
 gotidy:
 	$(MAKE) for-all CMD="rm -fr go.sum"
-	$(MAKE) for-all CMD="go mod tidy"
+	$(MAKE) for-all CMD="go mod tidy -go=1.16"
+	$(MAKE) for-all CMD="go mod tidy -go=1.17"
 
 .PHONY: addlicense
 addlicense:
