diff --git a/Makefile b/Makefile
index 23435666d..b8a90e08a 100644
--- a/Makefile
+++ b/Makefile
@@ -390,7 +390,8 @@ multimod-verify: install-tools
 
 .PHONY: multimod-prerelease
 multimod-prerelease: install-tools
-	multimod prerelease -s=true -b=false -v ./versions.yaml -m collector-core
+	multimod prerelease -s=true -b=false -v ./versions.yaml -m stable
+	multimod prerelease -s=true -b=false -v ./versions.yaml -m beta
 	$(MAKE) gotidy
 
 .PHONY: prepare-release
