diff --git a/scraper/scraperhelper/xscraperhelper/Makefile b/scraper/scraperhelper/xscraperhelper/Makefile
new file mode 100644
index 000000000..bdd863a20
--- /dev/null
+++ b/scraper/scraperhelper/xscraperhelper/Makefile
@@ -0,0 +1 @@
+include ../../../Makefile.Common
