diff --git a/Makefile b/Makefile
index b2c3714b5..0dcafc2ab 100644
--- a/Makefile
+++ b/Makefile
@@ -246,7 +246,7 @@ PROTO_PACKAGE=go.opentelemetry.io/collector/$(PROTO_TARGET_GEN_DIR)
 # Intermediate directory used during generation.
 PROTO_INTERMEDIATE_DIR=internal/data/.patched-otlp-proto
 
-DOCKER_PROTOBUF ?= otel/build-protobuf:latest
+DOCKER_PROTOBUF ?= otel/build-protobuf:0.1.0
 PROTOC := docker run --rm -u ${shell id -u} -v${PWD}:${PWD} -w${PWD}/$(PROTO_INTERMEDIATE_DIR) ${DOCKER_PROTOBUF} --proto_path=${PWD}
 PROTO_INCLUDES := -I/usr/include/github.com/gogo/protobuf -I./
 
