diff --git a/Makefile b/Makefile
index 7d733e090..e87808ce6 100644
--- a/Makefile
+++ b/Makefile
@@ -475,3 +475,7 @@ gengithub: $(GITHUBGEN) generate-codeowners generate-gh-issue-templates
 .PHONY: gendistributions
 gendistributions: $(GITHUBGEN)
 	$(GITHUBGEN) distributions
+
+.PHONY: generate-chloggen-components
+generate-chloggen-components: $(GITHUBGEN)
+	$(GITHUBGEN) chloggen-components
