diff --git a/Makefile b/Makefile
index b03c4a1b9..76c526ca1 100644
--- a/Makefile
+++ b/Makefile
@@ -242,7 +242,7 @@ binaries-windows_amd64:
 
 .PHONY: build-binary-internal
 build-binary-internal:
-	GO111MODULE=on CGO_ENABLED=0 go build -o ./bin/otelcol_$(GOOS)_$(GOARCH)$(EXTENSION) $(BUILD_INFO) ./cmd/otelcol
+	GO111MODULE=on CGO_ENABLED=0 go build -trimpath -o ./bin/otelcol_$(GOOS)_$(GOARCH)$(EXTENSION) $(BUILD_INFO) ./cmd/otelcol
 
 
 .PHONY: deb-rpm-package
