diff --git a/processor/processorhelper/processorhelperprofiles/Makefile b/processor/processorhelper/processorhelperprofiles/Makefile
deleted file mode 100644
index bdd863a20..000000000
--- a/processor/processorhelper/processorhelperprofiles/Makefile
+++ /dev/null
@@ -1 +0,0 @@
-include ../../../Makefile.Common
