diff --git a/processor/processortest/Makefile b/processor/processortest/Makefile
new file mode 100644
index 000000000..ded7a3609
--- /dev/null
+++ b/processor/processortest/Makefile
@@ -0,0 +1 @@
+include ../../Makefile.Common
