diff --git a/component/componentattribute/Makefile b/component/componentattribute/Makefile
deleted file mode 100644
index ded7a3609..000000000
--- a/component/componentattribute/Makefile
+++ /dev/null
@@ -1 +0,0 @@
-include ../../Makefile.Common
