diff --git a/consumer/consumererror/Makefile b/consumer/consumererror/Makefile
new file mode 100644
index 000000000..ded7a3609
--- /dev/null
+++ b/consumer/consumererror/Makefile
@@ -0,0 +1 @@
+include ../../Makefile.Common
