diff --git a/receiver/xreceiver/Makefile b/receiver/xreceiver/Makefile
new file mode 100644
index 000000000..ded7a3609
--- /dev/null
+++ b/receiver/xreceiver/Makefile
@@ -0,0 +1 @@
+include ../../Makefile.Common
