diff --git a/extension/auth/Makefile b/extension/auth/Makefile
deleted file mode 100644
index ded7a3609..000000000
--- a/extension/auth/Makefile
+++ /dev/null
@@ -1 +0,0 @@
-include ../../Makefile.Common
