diff --git a/Dockerfile b/Dockerfile
index 4fdea406b..4bacaa17e 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,8 +1,23 @@
-FROM debian:jessie
+FROM golang:1.11-alpine3.7 as builder
 
-COPY ./bin/ocagent_linux ocagent
+RUN apk update && apk upgrade && \
+    apk add --no-cache bash git openssh
 
-# Expose the OpenCensus interceptor port
+ENV GOPKG github.com/census-instrumentation/opencensus-service
+
+COPY . /go/src/$GOPKG/
+
+RUN go get $GOPKG/...
+RUN cd /go/src/$GOPKG/ && ./build_binaries.sh linux && cp /go/src/$GOPKG/bin/ocagent_linux /ocagent
+
+FROM alpine:3.7
+
+RUN apk update && apk upgrade && \
+    apk add --no-cache bash git openssh
+
+COPY --from=builder /ocagent /ocagent
+
+# Expose the OpenCensus interceptor port.
 EXPOSE 55678/tcp
 
-CMD ["ocagent"]
+CMD ["/ocagent"]
