diff --git a/Makefile b/Makefile
index bfee6971f..014988194 100644
--- a/Makefile
+++ b/Makefile
@@ -384,11 +384,7 @@ push-tags: $(MULTIMOD)
 
 .PHONY: check-changes
 check-changes: $(MULTIMOD)
-	# NOTE: ! inverses the return code of multimod diff. This is
-	# because prepare-release expects a 0 if there are diffs and
-	# non-0 if there are no diffs, which is the inverse of most
-	# diff tools
-	! $(MULTIMOD) diff -p $(PREVIOUS_VERSION) -m $(MODSET)
+	$(MULTIMOD) diff -p $(PREVIOUS_VERSION) -m $(MODSET)
 
 .PHONY: prepare-release
 prepare-release:
@@ -413,8 +409,6 @@ else
 endif
 	# ensure a clean branch
 	git diff -s --exit-code || (echo "local repository not clean"; exit 1)
-	# check if any modules have changed since the previous release
-	$(MAKE) check-changes
 	# update files with new version
 	sed -i.bak 's/$(PREVIOUS_VERSION)/$(RELEASE_CANDIDATE)/g' versions.yaml
 	sed -i.bak 's/$(PREVIOUS_VERSION)/$(RELEASE_CANDIDATE)/g' ./cmd/builder/internal/builder/config.go
