diff --git a/extension/storage/Makefile b/extension/storage/Makefile
new file mode 100644
index 000000000..ded7a3609
--- /dev/null
+++ b/extension/storage/Makefile
@@ -0,0 +1 @@
+include ../../Makefile.Common
