diff --git a/Makefile b/Makefile
index 19bc35672..e6701755c 100644
--- a/Makefile
+++ b/Makefile
@@ -26,7 +26,7 @@ BUILD_INFO=-ldflags "-X $(BUILD_INFO_IMPORT_PATH).Version=$(VERSION)"
 
 RUN_CONFIG?=examples/local/otel-config.yaml
 CONTRIB_PATH=$(CURDIR)/../opentelemetry-collector-contrib
-COMP_REL_PATH=service/defaultcomponents/defaults.go
+COMP_REL_PATH=cmd/otelcorecol/components.go
 MOD_NAME=go.opentelemetry.io/collector
 
 ADDLICENSE=addlicense
