diff --git a/service/telemetry/telemetrytest/Makefile b/service/telemetry/telemetrytest/Makefile
new file mode 100644
index 000000000..bdd863a20
--- /dev/null
+++ b/service/telemetry/telemetrytest/Makefile
@@ -0,0 +1 @@
+include ../../../Makefile.Common
