diff --git a/examples/demo/app/Dockerfile b/examples/demo/app/Dockerfile
index 97c758351..bd18c87ce 100644
--- a/examples/demo/app/Dockerfile
+++ b/examples/demo/app/Dockerfile
@@ -11,7 +11,7 @@
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
-FROM golang:1.14
+FROM golang:1.16
 COPY . /usr/src/app/
 WORKDIR /usr/src/app/
 RUN go env -w GOPROXY=direct
