diff --git a/Makefile b/Makefile
index 06bf3db25..f4be2ee6a 100644
--- a/Makefile
+++ b/Makefile
@@ -3,6 +3,7 @@ ALL_SRC := $(shell find . -type f -name '*.go' -not -path "./vendor/*")
 GOTEST_OPT?=-v -race
 GOTEST=go test
 GOFMT=gofmt
+GOLINT=golint
 GOOS=$(shell go env GOOS)
 
 GIT_SHA=$(shell git rev-parse --short HEAD)
@@ -12,7 +13,7 @@ BUILD_INFO=-ldflags "-X $(BUILD_INFO_IMPORT_PATH).GitHash=$(GIT_SHA)"
 .DEFAULT_GOAL := default_goal
 
 .PHONY: default_goal
-default_goal: fmt test
+default_goal: fmt lint test
 
 .PHONY: test
 test:
@@ -27,6 +28,19 @@ fmt:
 		exit 1; \
 	fi
 
+.PHONY: lint
+lint:
+	@LINTOUT=`$(GOLINT) ./... 2>&1`; \
+	if [ "$$LINTOUT" ]; then \
+		echo "$(GOLINT) FAILED => clean the following lint errors:\n"; \
+		echo "$$LINTOUT\n"; \
+		exit 1; \
+	fi
+
+.PHONY: install-tools
+install-tools:
+	go get -u golang.org/x/lint/golint
+
 .PHONY: agent
 agent:
 	CGO_ENABLED=0 go build -o ./bin/ocagent_$(GOOS) $(BUILD_INFO) ./cmd/ocagent
