diff --git a/extension/auth/authtest/Makefile b/extension/auth/authtest/Makefile
new file mode 100644
index 000000000..bdd863a20
--- /dev/null
+++ b/extension/auth/authtest/Makefile
@@ -0,0 +1 @@
+include ../../../Makefile.Common
