diff --git a/exporter/loggingexporter/Makefile b/exporter/loggingexporter/Makefile
new file mode 100644
index 000000000..ded7a3609
--- /dev/null
+++ b/exporter/loggingexporter/Makefile
@@ -0,0 +1 @@
+include ../../Makefile.Common
