diff --git a/config/confighttp/Makefile b/config/confighttp/Makefile
new file mode 100644
index 000000000..ded7a3609
--- /dev/null
+++ b/config/confighttp/Makefile
@@ -0,0 +1 @@
+include ../../Makefile.Common
