diff --git a/pdata/pprofile/Makefile b/pdata/pprofile/Makefile
new file mode 100644
index 000000000..ded7a3609
--- /dev/null
+++ b/pdata/pprofile/Makefile
@@ -0,0 +1 @@
+include ../../Makefile.Common
