diff --git a/examples/demo/server/Dockerfile b/examples/demo/server/Dockerfile
index f348a2092..050f9fcf7 100644
--- a/examples/demo/server/Dockerfile
+++ b/examples/demo/server/Dockerfile
@@ -11,7 +11,7 @@
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
-FROM golang:1.16
+FROM golang:1.17
 COPY . /usr/src/server/
 WORKDIR /usr/src/server/
 RUN go env -w GOPROXY=direct
