diff --git a/connector/connectorprofiles/Makefile b/connector/connectorprofiles/Makefile
deleted file mode 100644
index ded7a3609..000000000
--- a/connector/connectorprofiles/Makefile
+++ /dev/null
@@ -1 +0,0 @@
-include ../../Makefile.Common
