diff --git a/Makefile b/Makefile
index d2c30a214..a20712d29 100644
--- a/Makefile
+++ b/Makefile
@@ -243,6 +243,7 @@ genproto:
 	# Call a sub-make to ensure OPENTELEMETRY_PROTO_FILES is populated after the submodule
 	# files are present.
 	$(MAKE) genproto_sub
+	$(MAKE) fmt
 
 genproto_sub:
 	@echo Generating code for the following files:
