diff --git a/scraper/scrapertest/Makefile b/scraper/scrapertest/Makefile
new file mode 100644
index 000000000..ded7a3609
--- /dev/null
+++ b/scraper/scrapertest/Makefile
@@ -0,0 +1 @@
+include ../../Makefile.Common
